create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  vendedor text not null,
  endpoint text not null unique,
  p256dh text,
  auth text,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_vendedor_idx
  on public.push_subscriptions (vendedor);

alter table public.push_subscriptions enable row level security;

-- Nao crie policy publica para esta tabela.
-- O site registra e envia notificacoes pelo Cloudflare Worker usando SUPABASE_SERVICE_ROLE_KEY.
